name: Build and Push Docker Image to GHCR

on:
  repository_dispatch:
    types: [trigger-release]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code from Repo 1
        uses: actions/checkout@v3
        with:
          repository: jppanda92/go-webapp-mondoo
          token: ${{ secrets.CROSS_REPO_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/mondoo-webapp:${{ github.sha }} .
      
      - name: Set the Image Tag in Kubernetes YAML
        run: |
          sed -i 's|${IMAGE_TAG}|ghcr.io/${{ github.repository }}/mondoo-webapp:${{ github.sha }}|' deployment.yml    

      - name: Push the Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/mondoo-webapp:${{ github.sha }}

      - name: Install cnspec
        run: |
          curl -LO https://github.com/cncf/cnspec/releases/download/v0.1.1/cnspec-linux-amd64
          chmod +x cnspec-linux-amd64
          mv cnspec-linux-amd64 /usr/local/bin/cnspec
  
      - name: Run cnspec to validate the Docker image
        run: |
          cnspec check cnspec.yaml
