name: Build and Push Docker Image to GHCR

on:
  repository_dispatch:
    types: [trigger-release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code from Repo 1
        uses: actions/checkout@v3
        with:
          repository: jppanda92/go-webapp-mondoo
          token: ${{ secrets.CROSS_REPO_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/mondoo-webapp:${{ github.sha }} .

      - name: Push the Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/mondoo-webapp:${{ github.sha }}
